/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccreditationDto } from './accreditationDto';
import { AccreditationBatchRenewalResponseFailedInner } from './accreditationBatchRenewalResponseFailedInner';


/**
 * Response for batch accreditation renewal
 */
export interface AccreditationBatchRenewalResponse { 
    /**
     * Successfully renewed accreditations
     */
    renewed?: Array<AccreditationDto>;
    /**
     * Failed renewal attempts with error details
     */
    failed?: Array<AccreditationBatchRenewalResponseFailedInner>;
}

