/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { ClubDto } from './clubDto';
import { AccreditationStatus } from './accreditationStatus';
import { AthleteDto } from './athleteDto';


/**
 * Data Transfer Object representing an athlete accreditation with all its details
 */
export interface AccreditationDto { 
    /**
     * Unique identifier of the accreditation
     */
    uuid?: string;
    /**
     * UUID of the athlete
     */
    athleteId?: string;
    /**
     * UUID of the club
     */
    clubId?: string;
    club?: ClubDto;
    athlete?: AthleteDto;
    /**
     * Accreditation number
     */
    accreditationNumber?: string;
    /**
     * Year of the accreditation
     */
    year?: number;
    scopeType?: ScopeType;
    status?: AccreditationStatus;
    /**
     * Timestamp when the accreditation was created
     */
    createdAt?: string;
    /**
     * Timestamp when the accreditation was last modified
     */
    updatedAt?: string;
}
export namespace AccreditationDto {
}


