/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { AccreditationStatus } from './accreditationStatus';


/**
 * Request payload for creating a new accreditation
 */
export interface AccreditationCreateRequest { 
    /**
     * UUID of the athlete
     */
    athleteId: string;
    /**
     * UUID of the club
     */
    clubId: string;
    /**
     * Accreditation number
     */
    accreditationNumber: string;
    /**
     * Year of the accreditation
     */
    year: number;
    scopeType?: ScopeType;
    status?: AccreditationStatus;
}
export namespace AccreditationCreateRequest {
}


