/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccreditationStatus } from './accreditationStatus';


/**
 * Request body for updating accreditation status (single enum field)
 */
export interface AccreditationStatusUpdateRequest { 
    status: AccreditationStatus;
}
export namespace AccreditationStatusUpdateRequest {
}


