/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload for batch renewal of accreditations
 */
export interface AccreditationBatchRenewalRequest { 
    /**
     * List of athlete UUIDs to renew accreditations for (max 100 per request; send multiple requests for more)
     */
    athleteIds: Array<string>;
}

