/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccreditationStatus } from './accreditationStatus';


/**
 * Request body for PATCH accreditation status (single enum field)
 */
export interface AccreditationStatusPatchRequest { 
    status: AccreditationStatus;
}
export namespace AccreditationStatusPatchRequest {
}


