/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to advance participants to the next round
 */
export interface AdvanceRequest { 
    /**
     * UUID of the timetable event to advance from
     */
    eventId: string;
}

