/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisciplineProgressionResult } from './disciplineProgressionResult';


/**
 * Response with per-discipline advancement results
 */
export interface AdvanceProgressionResponse { 
    results?: Array<DisciplineProgressionResult>;
}

