/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to advance progression to the next stage for selected disciplines
 */
export interface AdvanceProgressionRequest { 
    /**
     * Disciplines to advance. Empty or null = all disciplines in competition.
     */
    disciplineIds?: Array<string>;
}

