/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubDto } from './clubDto';


/**
 * Data Transfer Object representing an athlete photo history entry
 */
export interface AthletePhotoDto { 
    /**
     * Unique identifier of the photo history entry
     */
    uuid?: string;
    /**
     * UUID of the athlete
     */
    athleteId?: string;
    /**
     * When returned from getAthletePhotos, a full URL (e.g. time-limited presigned URL) suitable for direct use as an image source. The stored value in the system may be an internal path.
     */
    photoUrl?: string;
    /**
     * Timestamp when the photo was uploaded
     */
    uploadedAt?: string;
    /**
     * UUID of the club that uploaded the photo
     */
    uploadedById?: string;
    uploadedBy?: ClubDto;
}

