/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload for batch update of medical and insurance information. At least one pair (insurance or medical examination) must be provided.
 */
export interface AthleteBatchMedicalUpdateRequest { 
    /**
     * List of athlete UUIDs to update (max 100 per request; send multiple requests for more)
     */
    athleteIds: Array<string>;
    /**
     * Insurance start date (required if insuranceTo is provided)
     */
    insuranceFrom?: string;
    /**
     * Insurance end date (required if insuranceFrom is provided)
     */
    insuranceTo?: string;
    /**
     * Medical examination start date (required if medicalExaminationDurationMonths is provided)
     */
    medicalExaminationStartDate?: string;
    /**
     * Medical examination duration in months (required if medicalExaminationStartDate is provided)
     */
    medicalExaminationDurationMonths?: number;
}

