/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AthleteBatchMigrationRequestItem } from './athleteBatchMigrationRequestItem';


export interface AthleteBatchMigrationResponseSkippedInner { 
    athlete?: AthleteBatchMigrationRequestItem;
    /**
     * Reason why the athlete was skipped
     */
    reason?: string;
}

