/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { Gender } from './gender';


/**
 * Data Transfer Object representing an athlete with all their details
 */
export interface AthleteDto { 
    uuid?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    dateOfBirth?: string;
    gender?: Gender;
    scopeType?: ScopeType;
    medicalExaminationDue?: string;
    insuranceFrom?: string;
    insuranceTo?: string;
    registeredOn?: string;
    /**
     * Timestamp when the athlete was last modified
     */
    modifiedAt?: string;
}
export namespace AthleteDto {
}


