/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gender } from './gender';


/**
 * Request payload for updating an existing athlete\'s information
 */
export interface AthleteUpdateRequest { 
    firstName: string;
    middleName?: string;
    lastName: string;
    gender: Gender;
    dateOfBirth: string;
    medicalExaminationDue?: string;
    insuranceFrom?: string;
    insuranceTo?: string;
}
export namespace AthleteUpdateRequest {
}


