/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gender } from './gender';


/**
 * Request payload for creating a new athlete (used by athletes themselves)
 */
export interface AthleteCreateRequest { 
    firstName: string;
    middleName: string;
    lastName: string;
    gender: Gender;
    dateOfBirth: string;
}
export namespace AthleteCreateRequest {
}


