/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of rowing boat
 */
export const BoatClass = {
    _1X: '1X',
    _2X: '2X',
    _2: '2+',
    _22: '2-',
    _4X: '4X',
    _4X2: '4X+',
    _4: '4+',
    _42: '4-',
    _8: '8+',
    Ergo: 'ERGO'
} as const;
export type BoatClass = typeof BoatClass[keyof typeof BoatClass];

