/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of rowing boat
 */
export const BoatClass = {
    SingleScull: 'SINGLE_SCULL',
    DoubleScull: 'DOUBLE_SCULL',
    CoxedPair: 'COXED_PAIR',
    Pair: 'PAIR',
    Quad: 'QUAD',
    CoxedQuad: 'COXED_QUAD',
    CoxedFour: 'COXED_FOUR',
    Four: 'FOUR',
    Eight: 'EIGHT',
    Ergo: 'ERGO'
} as const;
export type BoatClass = typeof BoatClass[keyof typeof BoatClass];

