/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';


/**
 * Request payload for updating an existing rowing club
 */
export interface ClubUpdateRequest { 
    name?: string;
    shortName?: string;
    /**
     * Whether the club is active
     */
    isActive?: boolean;
    /**
     * UUID of the club administrator user
     */
    clubAdminId?: string;
    type?: ScopeType;
}
export namespace ClubUpdateRequest {
}


