/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubBatchCreateRequestItem } from './clubBatchCreateRequestItem';


export interface ClubBatchCreateResponseSkippedInner { 
    club?: ClubBatchCreateRequestItem;
    /**
     * Reason why the club was skipped
     */
    reason?: string;
}

