/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to compute club rankings across multiple competitions
 */
export interface ClubRankingsRequest { 
    competitionIds: Array<string>;
}

