/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubBatchCreateRequestItem } from './clubBatchCreateRequestItem';


/**
 * Request payload for batch creating clubs with admin email
 */
export interface ClubBatchCreateRequest { 
    /**
     * At most 100 clubs per request are allowed.
     */
    clubs: Array<ClubBatchCreateRequestItem>;
}

