/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubDto } from './clubDto';
import { ClubBatchCreateResponseSkippedInner } from './clubBatchCreateResponseSkippedInner';


/**
 * Response for batch club creation
 */
export interface ClubBatchCreateResponse { 
    /**
     * Successfully created clubs
     */
    created?: Array<ClubDto>;
    /**
     * Clubs that were skipped due to errors
     */
    skipped?: Array<ClubBatchCreateResponseSkippedInner>;
}

