/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Single club item for batch creation
 */
export interface ClubBatchCreateRequestItem { 
    name: string;
    shortName: string;
    /**
     * Prefix for athlete card numbers (must be exactly 2 digits, 01-99)
     */
    cardPrefix: string;
    clubEmail: string;
    /**
     * Email address of the club administrator user
     */
    adminEmail: string;
}

