/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryDto } from './entryDto';


/**
 * Response payload containing all entries for a club in a competition
 */
export interface ClubEntriesDto { 
    entries?: Array<EntryDto>;
    /**
     * True when entries are modified during RACE phase and progression data already exists. Indicates progression may need regeneration.
     */
    progressionWarning?: boolean;
}

