/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubRankingDto } from './clubRankingDto';


/**
 * Response with club rankings aggregated across competitions
 */
export interface ClubRankingsResponse { 
    rankings?: Array<ClubRankingDto>;
}

