/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubRankingDisciplineDto } from './clubRankingDisciplineDto';


/**
 * Points breakdown for a single competition within a club ranking
 */
export interface ClubRankingCompetitionDto { 
    competitionId?: string;
    competitionName?: string;
    competitionPoints?: number;
    disciplines?: Array<ClubRankingDisciplineDto>;
}

