/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';
import { QualificationEventType } from './qualificationEventType';


/**
 * Data Transfer Object for competition event timetable
 */
export interface CompetitionEventTimetableDto { 
    uuid?: string;
    competitionId?: string;
    eventNumber?: number;
    disciplineId?: string;
    qualificationEventType?: QualificationEventType;
    qualificationStageNumber?: number;
    scheduledAt?: string;
    startedAt?: string;
    competitionEventStatus?: CompetitionEventStatus;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionEventTimetableDto {
}


