/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';
import { QualificationEventType } from './qualificationEventType';
import { DisciplineDefinitionDto } from './disciplineDefinitionDto';


/**
 * Data Transfer Object for competition timetable event
 */
export interface CompetitionTimetableEventDto { 
    uuid?: string;
    competitionId?: string;
    disciplineId?: string;
    discipline?: DisciplineDefinitionDto;
    qualificationEventType?: QualificationEventType;
    scheduledAt?: string;
    eventStatus?: CompetitionEventStatus;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionTimetableEventDto {
}


