/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionType } from './competitionType';


/**
 * Request payload for creating a competition
 */
export interface CompetitionCreateRequest { 
    shortName: string;
    name: string;
    location: string;
    startDate: string;
    endDate: string;
    /**
     * Required when isTemplate is false.
     */
    entrySubmissionsOpenAt?: string;
    /**
     * Required when isTemplate is false.
     */
    entrySubmissionsClosedAt?: string;
    /**
     * Required when isTemplate is false.
     */
    lastChangesBeforeTmAt?: string;
    /**
     * Required when isTemplate is false.
     */
    technicalMeetingAt?: string;
    /**
     * Required when isTemplate is false. Must be on the endDate.
     */
    awardingCeremonyAt?: string;
    scoringSchemeId: string;
    qualificationSchemeId: string;
    competitionType: CompetitionType;
    isTemplate: boolean;
}
export namespace CompetitionCreateRequest {
}


