/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a competition
 */
export const CompetitionStatus = {
    Planned: 'PLANNED',
    RegistrationOpen: 'REGISTRATION_OPEN',
    RegistrationClosed: 'REGISTRATION_CLOSED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type CompetitionStatus = typeof CompetitionStatus[keyof typeof CompetitionStatus];

