/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualificationEventType } from './qualificationEventType';


/**
 * Data Transfer Object for competition event timetable template
 */
export interface CompetitionEventTimetableTemplateDto { 
    uuid?: string;
    competitionTemplateId?: string;
    eventNumber?: number;
    disciplineCode?: string;
    qualificationEventType?: QualificationEventType;
    qualificationStageNumber?: number;
    dayOffset?: number;
    plannedTime?: string;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionEventTimetableTemplateDto {
}


