/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionGroupGender } from './competitionGroupGender';
import { TransferRounding } from './transferRounding';


/**
 * Request payload for creating or updating a competition group definition
 */
export interface CompetitionGroupDefinitionRequest { 
    name: string;
    shortName: string;
    gender: CompetitionGroupGender;
    minAge: number;
    maxAge: number;
    /**
     * Nullable - all transfer fields must be set together or all null
     */
    transferFromGroupId?: string;
    /**
     * Nullable - all transfer fields must be set together or all null
     */
    minCrewForTransfer?: number;
    /**
     * Nullable - all transfer fields must be set together or all null
     */
    transferRatio?: number;
    transferRounding?: TransferRounding;
    /**
     * Nullable - both cox weight fields must be set together or both null
     */
    coxRequiredWeightKg?: number;
    /**
     * Nullable - both cox weight fields must be set together or both null
     */
    coxMinWeightKg?: number;
    lightMaxWeightKg?: number;
    isActive: boolean;
}
export namespace CompetitionGroupDefinitionRequest {
}


