/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';
import { QualificationEventType } from './qualificationEventType';


/**
 * Request payload for creating or updating a competition timetable event
 */
export interface CompetitionTimetableEventRequest { 
    competitionId: string;
    disciplineId: string;
    qualificationEventType: QualificationEventType;
    scheduledAt: string;
    eventStatus: CompetitionEventStatus;
}
export namespace CompetitionTimetableEventRequest {
}


