/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferRounding } from './transferRounding';


/**
 * Data Transfer Object for competition group definition
 */
export interface CompetitionGroupDefinitionDto { 
    uuid?: string;
    name?: string;
    shortName?: string;
    minAge?: number;
    maxAge?: number;
    /**
     * Minimum age for coxswain - nullable, falls back to minAge
     */
    coxMinAge?: number;
    /**
     * Maximum age for coxswain - nullable, falls back to maxAge
     */
    coxMaxAge?: number;
    maxDisciplinesPerAthlete?: number;
    transferFromGroupId?: string;
    minCrewForTransfer?: number;
    transferRatio?: number;
    transferRounding?: TransferRounding;
    transferredMaxDisciplinesPerAthlete?: number;
    maleTeamCoxRequiredWeightKg?: number;
    maleTeamCoxMinWeightKg?: number;
    maleTeamLightMaxWeightKg?: number;
    femaleTeamCoxRequiredWeightKg?: number;
    femaleTeamCoxMinWeightKg?: number;
    femaleTeamLightMaxWeightKg?: number;
    isActive?: boolean;
    transferFromGroup?: CompetitionGroupDefinitionDto;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionGroupDefinitionDto {
}


