/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionTimetableEventRequest } from './competitionTimetableEventRequest';


/**
 * Request payload for bulk upserting timetable events for a competition
 */
export interface CompetitionTimetableEventBulkRequest { 
    competitionId: string;
    events: Array<CompetitionTimetableEventRequest>;
}

