/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to assign a discipline to a competition template
 */
export interface CompetitionTemplateDisciplineCreateRequest { 
    competitionTemplateId: string;
    disciplineId: string;
}

