/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualificationEventType } from './qualificationEventType';


/**
 * Request payload for updating an event timetable template entry
 */
export interface CompetitionEventTimetableTemplateUpdateRequest { 
    eventNumber?: number;
    disciplineCode?: string;
    qualificationEventType?: QualificationEventType;
    qualificationStageNumber?: number;
    dayOffset?: number;
    plannedTime?: string;
}
export namespace CompetitionEventTimetableTemplateUpdateRequest {
}


