/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { CompetitionStatus } from './competitionStatus';


/**
 * Data Transfer Object for competition
 */
export interface CompetitionDto { 
    uuid?: string;
    shortName?: string;
    name?: string;
    season?: number;
    location?: string;
    startDate?: string;
    endDate?: string;
    status?: CompetitionStatus;
    scopeType?: ScopeType;
    scoringSchemeId?: string;
    qualificationSchemeId?: string;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionDto {
}


