/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to compute final standings for disciplines
 */
export interface ComputeStandingsRequest { 
    disciplineIds: Array<string>;
}

