/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data Transfer Object for competition discipline assignment
 */
export interface CompetitionDisciplineDto { 
    uuid?: string;
    competitionId?: string;
    disciplineId?: string;
    createdAt?: string;
    modifiedAt?: string;
}

