/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';
import { QualificationEventType } from './qualificationEventType';


/**
 * Request payload for creating or updating a competition timetable event
 */
export interface CompetitionTimetableEventRequest { 
    competitionId: string;
    eventNumber: number;
    disciplineId: string;
    qualificationEventType: QualificationEventType;
    qualificationStageNumber: number;
    dayOffset: number;
    plannedTime: string;
    /**
     * Null for templates; full datetime for real competition events
     */
    scheduledAt?: string;
    eventStatus: CompetitionEventStatus;
}
export namespace CompetitionTimetableEventRequest {
}


