/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type/format of the competition
 */
export const CompetitionType = {
    Standard: 'STANDARD',
    Erg: 'ERG',
    NationalTeamTest: 'NATIONAL_TEAM_TEST'
} as const;
export type CompetitionType = typeof CompetitionType[keyof typeof CompetitionType];

