/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a competition event
 */
export const CompetitionEventStatus = {
    Scheduled: 'SCHEDULED',
    InProgress: 'IN_PROGRESS',
    Finished: 'FINISHED',
    Cancelled: 'CANCELLED',
    Postponed: 'POSTPONED'
} as const;
export type CompetitionEventStatus = typeof CompetitionEventStatus[keyof typeof CompetitionEventStatus];

