/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload for updating a competition template
 */
export interface CompetitionTemplateUpdateRequest { 
    shortName?: string;
    name?: string;
    durationDays?: number;
    scoringSchemeId?: string;
    qualificationSchemeId?: string;
    isActive?: boolean;
}

