/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { CompetitionStatus } from './competitionStatus';


/**
 * Request payload for creating or updating a competition (template or real)
 */
export interface CompetitionRequest { 
    isTemplate: boolean;
    shortName: string;
    name: string;
    durationDays: number;
    /**
     * Required when isTemplate=false
     */
    season?: number;
    /**
     * Required when isTemplate=false
     */
    location?: string;
    /**
     * Required when isTemplate=false
     */
    startDate?: string;
    /**
     * Required when isTemplate=false
     */
    endDate?: string;
    /**
     * Required when isTemplate=false
     */
    status: CompetitionStatus;
    scopeType: ScopeType;
    scoringSchemeId: string;
    qualificationSchemeId: string;
}
export namespace CompetitionRequest {
}


