/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { CompetitionStatus } from './competitionStatus';


/**
 * Data Transfer Object for a competition (DRAFT status = template, non-DRAFT = real)
 */
export interface CompetitionDto { 
    uuid?: string;
    shortName?: string;
    name?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    /**
     * Required when status is not DRAFT.
     */
    entrySubmissionsOpenAt?: string;
    /**
     * Required when status is not DRAFT.
     */
    entrySubmissionsClosedAt?: string;
    /**
     * Required when status is not DRAFT.
     */
    lastChangesBeforeTmAt?: string;
    /**
     * Required when status is not DRAFT.
     */
    technicalMeetingAt?: string;
    status?: CompetitionStatus;
    scopeType?: ScopeType;
    scoringSchemeId?: string;
    qualificationSchemeId?: string;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CompetitionDto {
}


