/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeatPosition } from './seatPosition';


/**
 * Request payload for a single crew member seat assignment
 */
export interface CrewMemberRequest { 
    seatPosition: SeatPosition;
    accreditationId: string;
}
export namespace CrewMemberRequest {
}


