/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeatPosition } from './seatPosition';


/**
 * Data Transfer Object for crew member
 */
export interface CrewMemberDto { 
    uuid?: string;
    entryId?: string;
    seatPosition?: SeatPosition;
    athleteId?: string;
    cardNumber?: string;
    createdAt?: string;
    modifiedAt?: string;
}
export namespace CrewMemberDto {
}


