/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatClass } from './boatClass';


/**
 * Request payload for creating or updating a discipline definition
 */
export interface DisciplineDefinitionRequest { 
    name: string;
    shortName: string;
    competitionGroupId: string;
    boatClass: BoatClass;
    maxCrewFromTransfer: number;
    isLightweight: boolean;
    distanceMeters: number;
    isActive: boolean;
}
export namespace DisciplineDefinitionRequest {
}


