/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressionGenerationStatus } from './progressionGenerationStatus';


/**
 * Result of standings computation for a single discipline
 */
export interface DisciplineStandingResult { 
    disciplineId?: string;
    disciplineName?: string;
    status?: ProgressionGenerationStatus;
    reason?: string;
}
export namespace DisciplineStandingResult {
}


