/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gender classification for a discipline
 */
export const DisciplineGender = {
    Male: 'MALE',
    Female: 'FEMALE',
    Mixed: 'MIXED'
} as const;
export type DisciplineGender = typeof DisciplineGender[keyof typeof DisciplineGender];

