/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgressionGenerationStatus } from './progressionGenerationStatus';


/**
 * Result of progression advancement for a single discipline
 */
export interface DisciplineProgressionResult { 
    disciplineId?: string;
    disciplineName?: string;
    status?: ProgressionGenerationStatus;
    reason?: string;
    /**
     * Source stage (H, SF) advanced from. Null for first-stage generation.
     */
    fromStage?: string;
    /**
     * Generated/destination stage: H, SF, FA, etc.
     */
    stage?: string;
    eventCount?: number;
    entryCount?: number;
}
export namespace DisciplineProgressionResult {
}


