/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data Transfer Object for competition entry
 */
export interface EntryDto { 
    uuid?: string;
    competitionId?: string;
    clubId?: string;
    disciplineId?: string;
    teamNumber?: number;
    createdAt?: string;
    modifiedAt?: string;
}

