/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubDto } from './clubDto';
import { CrewMemberDto } from './crewMemberDto';


/**
 * Data Transfer Object for competition entry
 */
export interface EntryDto { 
    uuid?: string;
    competitionId?: string;
    clubId?: string;
    club?: ClubDto;
    disciplineId?: string;
    teamNumber?: number;
    crewMembers?: Array<CrewMemberDto>;
    createdAt?: string;
    modifiedAt?: string;
}

