/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CrewMemberRequest } from './crewMemberRequest';


/**
 * Request payload for a single entry (one team in one discipline)
 */
export interface EntryRequest { 
    disciplineId: string;
    teamNumber: number;
    crewMembers: Array<CrewMemberRequest>;
}

