/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Standard error response format used across all API endpoints
 */
export interface ErrorResponse { 
    /**
     * HTTP status code of the error
     */
    code?: number;
    /**
     * Error message description
     */
    message?: string;
}

