/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Finish status of a participation
 */
export const FinishStatus = {
    Ok: 'OK',
    Dns: 'DNS',
    Dnf: 'DNF',
    Dsq: 'DSQ'
} as const;
export type FinishStatus = typeof FinishStatus[keyof typeof FinishStatus];

