/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClubDto } from './clubDto';
import { PageSort } from './pageSort';


export interface GetAllClubs200Response { 
    content: Array<ClubDto>;
    /**
     * Total number of elements across all pages
     */
    totalElements: number;
    /**
     * Total number of pages
     */
    totalPages?: number;
    /**
     * Number of elements per page
     */
    size?: number;
    /**
     * Current page number (0-based)
     */
    number?: number;
    /**
     * Number of elements in the current page
     */
    numberOfElements?: number;
    /**
     * Whether this is the first page
     */
    first?: boolean;
    /**
     * Whether this is the last page
     */
    last?: boolean;
    /**
     * Whether the page is empty
     */
    empty?: boolean;
    sort?: PageSort;
}

