/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sort information
 */
export interface PageSort { 
    sorted?: boolean;
    unsorted?: boolean;
    empty?: boolean;
}

