/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a participation in a competition event
 */
export const ParticipationStatus = {
    Registered: 'REGISTERED',
    CheckedIn: 'CHECKED_IN',
    Dns: 'DNS',
    Dnf: 'DNF',
    Dsq: 'DSQ',
    Finished: 'FINISHED'
} as const;
export type ParticipationStatus = typeof ParticipationStatus[keyof typeof ParticipationStatus];

