/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipationStatus } from './participationStatus';


/**
 * Result for a single participation in a race event
 */
export interface ParticipationResultRequest { 
    participationId: string;
    finishStatus: ParticipationStatus;
    /**
     * Finish time in milliseconds. Required when finishStatus is FINISHED.
     */
    finishTimeMs?: number;
}
export namespace ParticipationResultRequest {
}


