/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of competition event (heat, semi-final, final)
 */
export const QualificationEventType = {
    H: 'H',
    Sf: 'SF',
    Fb: 'FB',
    Fa: 'FA'
} as const;
export type QualificationEventType = typeof QualificationEventType[keyof typeof QualificationEventType];

