/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';
import { ParticipationResultRequest } from './participationResultRequest';


/**
 * Request to record results for a race event
 */
export interface RecordResultsRequest { 
    results: Array<ParticipationResultRequest>;
    eventStatus: CompetitionEventStatus;
}
export namespace RecordResultsRequest {
}


