/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to reset password using a token
 */
export interface ResetPasswordRequest { 
    token: string;
    newPassword: string;
}

