/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Seat position in a boat
 */
export const SeatPosition = {
    Bow: 'BOW',
    Two: 'TWO',
    Three: 'THREE',
    Four: 'FOUR',
    Five: 'FIVE',
    Six: 'SIX',
    Seven: 'SEVEN',
    Stroke: 'STROKE',
    Cox: 'COX'
} as const;
export type SeatPosition = typeof SeatPosition[keyof typeof SeatPosition];

