/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of user system roles
 */
export const SystemRole = {
    AppAdmin: 'APP_ADMIN',
    FederationAdmin: 'FEDERATION_ADMIN',
    ClubAdmin: 'CLUB_ADMIN',
    Coach: 'COACH'
} as const;
export type SystemRole = typeof SystemRole[keyof typeof SystemRole];

