/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionEventStatus } from './competitionEventStatus';


/**
 * Request to update the status of a competition timetable event
 */
export interface UpdateEventStatusRequest { 
    eventStatus: CompetitionEventStatus;
}
export namespace UpdateEventStatusRequest {
}


