/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload for updating an existing user (partial update). Email and role cannot be updated.
 */
export interface UserUpdateRequest { 
    firstName: string;
    lastName: string;
    dateOfBirth?: string;
    username?: string;
    isActive?: boolean;
}

