/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemRole } from './systemRole';


/**
 * Data Transfer Object representing a system user
 */
export interface UserDto { 
    /**
     * Unique identifier of the user
     */
    uuid?: string;
    /**
     * First name of the user
     */
    firstName?: string;
    /**
     * Last name of the user
     */
    lastName?: string;
    /**
     * Date of birth
     */
    dateOfBirth?: string;
    /**
     * Username for login
     */
    username?: string;
    /**
     * Email address
     */
    email?: string;
    /**
     * Whether the user account is active
     */
    isActive?: boolean;
    role?: SystemRole;
    /**
     * Account creation timestamp
     */
    createdAt?: string;
    /**
     * Last modification timestamp
     */
    updatedAt?: string;
    /**
     * Whether the user is currently assigned to a club (as coach or club admin)
     */
    assignedToClub?: boolean;
}
export namespace UserDto {
}


