/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeType } from './scopeType';
import { SystemRole } from './systemRole';


/**
 * Request payload for creating a new user
 */
export interface UserCreateRequest { 
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    /**
     * Username for login (optional, will be set to email if not provided for coaches created by club admins)
     */
    username?: string;
    email: string;
    role: SystemRole;
    scopeType?: ScopeType;
}
export namespace UserCreateRequest {
}


