/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBatchMigrationRequestItem } from './userBatchMigrationRequestItem';


/**
 * A user that was skipped during migration with the reason
 */
export interface UserBatchMigrationSkippedItem { 
    user?: UserBatchMigrationRequestItem;
    /**
     * Reason why the user was skipped
     */
    reason?: string;
}

