/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Role of the athlete for weight measurement purposes
 */
export const WeightMeasurementRole = {
    Rower: 'ROWER',
    Cox: 'COX'
} as const;
export type WeightMeasurementRole = typeof WeightMeasurementRole[keyof typeof WeightMeasurementRole];

