/**
 * BFG API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { AccreditationBatchRenewalRequest } from '../model/accreditationBatchRenewalRequest';
// @ts-ignore
import { AccreditationBatchRenewalResponse } from '../model/accreditationBatchRenewalResponse';
// @ts-ignore
import { AccreditationDto } from '../model/accreditationDto';
// @ts-ignore
import { AccreditationStatusPatchRequest } from '../model/accreditationStatusPatchRequest';
// @ts-ignore
import { AthleteBatchMigrationRequest } from '../model/athleteBatchMigrationRequest';
// @ts-ignore
import { AthleteBatchMigrationResponse } from '../model/athleteBatchMigrationResponse';
// @ts-ignore
import { AthleteCreateRequest } from '../model/athleteCreateRequest';
// @ts-ignore
import { AthleteDto } from '../model/athleteDto';
// @ts-ignore
import { ErrorResponse } from '../model/errorResponse';
// @ts-ignore
import { GetAllAccreditations200Response } from '../model/getAllAccreditations200Response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class AccreditationsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Batch migrate athletes from old card number format
     * @param athleteBatchMigrationRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public batchMigrateAthletes(athleteBatchMigrationRequest: AthleteBatchMigrationRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AthleteBatchMigrationResponse>;
    public batchMigrateAthletes(athleteBatchMigrationRequest: AthleteBatchMigrationRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AthleteBatchMigrationResponse>>;
    public batchMigrateAthletes(athleteBatchMigrationRequest: AthleteBatchMigrationRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AthleteBatchMigrationResponse>>;
    public batchMigrateAthletes(athleteBatchMigrationRequest: AthleteBatchMigrationRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (athleteBatchMigrationRequest === null || athleteBatchMigrationRequest === undefined) {
            throw new Error('Required parameter athleteBatchMigrationRequest was null or undefined when calling batchMigrateAthletes.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations/migrate`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AthleteBatchMigrationResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: athleteBatchMigrationRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Batch renew accreditations for multiple athletes
     * Renews accreditations for the current year for multiple athletes. Uses the same card number if the athlete already has an accreditation for this club, otherwise generates a new one. Club ID is taken from the current user\&#39;s context. Maximum 100 athletes per request.
     * @param accreditationBatchRenewalRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public batchRenewAccreditations(accreditationBatchRenewalRequest: AccreditationBatchRenewalRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AccreditationBatchRenewalResponse>;
    public batchRenewAccreditations(accreditationBatchRenewalRequest: AccreditationBatchRenewalRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AccreditationBatchRenewalResponse>>;
    public batchRenewAccreditations(accreditationBatchRenewalRequest: AccreditationBatchRenewalRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AccreditationBatchRenewalResponse>>;
    public batchRenewAccreditations(accreditationBatchRenewalRequest: AccreditationBatchRenewalRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (accreditationBatchRenewalRequest === null || accreditationBatchRenewalRequest === undefined) {
            throw new Error('Required parameter accreditationBatchRenewalRequest was null or undefined when calling batchRenewAccreditations.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations/renew/batch`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AccreditationBatchRenewalResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: accreditationBatchRenewalRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a new athlete with accreditation
     * Creates a new athlete and automatically creates an accreditation for the current year. If an athlete with the same name and date of birth already exists, uses that athlete and creates only the accreditation. Club ID is taken from the current user\&#39;s context.
     * @param athleteCreateRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAthleteWithAccreditation(athleteCreateRequest: AthleteCreateRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AthleteDto>;
    public createAthleteWithAccreditation(athleteCreateRequest: AthleteCreateRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AthleteDto>>;
    public createAthleteWithAccreditation(athleteCreateRequest: AthleteCreateRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AthleteDto>>;
    public createAthleteWithAccreditation(athleteCreateRequest: AthleteCreateRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (athleteCreateRequest === null || athleteCreateRequest === undefined) {
            throw new Error('Required parameter athleteCreateRequest was null or undefined when calling createAthleteWithAccreditation.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AthleteDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: athleteCreateRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete accreditation
     * Deletes an accreditation by UUID. Only FEDERATION_ADMIN and APP_ADMIN can delete accreditations.
     * @param accreditationUuid UUID of the accreditation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAccreditation(accreditationUuid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteAccreditation(accreditationUuid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteAccreditation(accreditationUuid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteAccreditation(accreditationUuid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (accreditationUuid === null || accreditationUuid === undefined) {
            throw new Error('Required parameter accreditationUuid was null or undefined when calling deleteAccreditation.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations/${this.configuration.encodeParam({name: "accreditationUuid", value: accreditationUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get accreditation by UUID
     * @param accreditationUuid UUID of the accreditation
     * @param expand Fields to expand (multiselect). Available options: athlete, club  When expanded, the full entity objects are included in the response. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAccreditationByUuid(accreditationUuid: string, expand?: Array<'athlete' | 'club'>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AccreditationDto>;
    public getAccreditationByUuid(accreditationUuid: string, expand?: Array<'athlete' | 'club'>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AccreditationDto>>;
    public getAccreditationByUuid(accreditationUuid: string, expand?: Array<'athlete' | 'club'>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AccreditationDto>>;
    public getAccreditationByUuid(accreditationUuid: string, expand?: Array<'athlete' | 'club'>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (accreditationUuid === null || accreditationUuid === undefined) {
            throw new Error('Required parameter accreditationUuid was null or undefined when calling getAccreditationByUuid.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (expand) {
            expand.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'expand');
            })
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations/${this.configuration.encodeParam({name: "accreditationUuid", value: accreditationUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AccreditationDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all accreditations
     * @param filter Filter expression. Supports expanded fields with dot notation, range operator, and in operator.  **Available Fields:** - &#x60;athleteId&#x60;, &#x60;clubId&#x60; (UUID) - &#x60;year&#x60; or &#x60;accreditationYear&#x60; - &#x60;status&#x60; or &#x60;accreditationStatus&#x60; - &#x60;accreditationNumber&#x60; - &#x60;createdAt&#x60;, &#x60;modifiedAt&#x60;  **Expanded Fields (requires expand parameter):** - &#x60;athlete.dateOfBirth&#x60;, &#x60;athlete.firstName&#x60;, &#x60;athlete.middleName&#x60;, &#x60;athlete.lastName&#x60;, &#x60;athlete.gender&#x60; - &#x60;athlete.medicalExaminationDue&#x60;, &#x60;athlete.insuranceFrom&#x60;, &#x60;athlete.insuranceTo&#x60; - &#x60;club.name&#x60;, &#x60;club.shortName&#x60;, &#x60;club.isActive&#x60;  **Operators:** - Comparison: &#x60;eq&#x60;, &#x60;ne&#x60;, &#x60;gt&#x60;, &#x60;ge&#x60;, &#x60;lt&#x60;, &#x60;le&#x60; - Range: &#x60;field range \&#39;min\&#39; to \&#39;max\&#39;&#x60; (inclusive), &#x60;field range \&#39;min\&#39; to \&#39;\&#39;&#x60; (after min), &#x60;field range \&#39;\&#39; to \&#39;max\&#39;&#x60; (before max) - In: &#x60;field in (\&#39;value1\&#39;, \&#39;value2\&#39;, \&#39;value3\&#39;)&#x60;  **Examples:** - &#x60;clubId eq \&#39;xxx\&#39; and year eq 2025&#x60; - &#x60;athlete.dateOfBirth range \&#39;2002-01-01\&#39; to \&#39;2010-01-01\&#39;&#x60; (requires expand&#x3D;athlete) - &#x60;athlete.dateOfBirth range \&#39;2002-01-01\&#39; to \&#39;\&#39;&#x60; (after date, requires expand&#x3D;athlete) - &#x60;athlete.medicalExaminationDue lt \&#39;2026-03-01\&#39;&#x60; (requires expand&#x3D;athlete) - &#x60;athlete.insuranceTo ge \&#39;2026-01-01\&#39;&#x60; (requires expand&#x3D;athlete) - &#x60;status in (\&#39;ACTIVE\&#39;, \&#39;PENDING\&#39;)&#x60; - &#x60;clubId in (\&#39;uuid1\&#39;, \&#39;uuid2\&#39;, \&#39;uuid3\&#39;)&#x60; - &#x60;club.name eq \&#39;RC Sofia\&#39;&#x60; (requires expand&#x3D;club) 
     * @param search Free-text search across athlete names/date of birth, club name, and accreditation number (case-insensitive).  **Behavior:** - Tokenized by whitespace. - All tokens must match at least one field (AND across tokens).  **Matches:** - athlete &#x60;firstName&#x60;, &#x60;middleName&#x60;, &#x60;lastName&#x60; - athlete &#x60;dateOfBirth&#x60; when a token is a date (yyyy-MM-dd) - club &#x60;name&#x60; - &#x60;accreditationNumber&#x60;  **Examples:** - &#x60;Ivanov 1990-01-15 RC Sofia 000123&#x60; 
     * @param orderBy Sort fields (multiselect). Supports expanded fields with dot notation.  **Available Sorts:** - &#x60;year_asc&#x60;, &#x60;year_desc&#x60; - &#x60;accreditationNumber_asc&#x60;, &#x60;accreditationNumber_desc&#x60; - &#x60;createdAt_asc&#x60;, &#x60;createdAt_desc&#x60; - &#x60;modifiedAt_asc&#x60;, &#x60;modifiedAt_desc&#x60; (sorts by modification date; response field is &#x60;updatedAt&#x60;)  **Expanded Field Sorts (requires expand parameter):** - &#x60;athlete.dateOfBirth_asc&#x60;, &#x60;athlete.dateOfBirth_desc&#x60; - &#x60;athlete.firstName_asc&#x60;, &#x60;athlete.firstName_desc&#x60; - &#x60;athlete.middleName_asc&#x60;, &#x60;athlete.middleName_desc&#x60; - &#x60;athlete.lastName_asc&#x60;, &#x60;athlete.lastName_desc&#x60; - &#x60;athlete.gender_asc&#x60;, &#x60;athlete.gender_desc&#x60; - &#x60;athlete.medicalExaminationDue_asc&#x60;, &#x60;athlete.medicalExaminationDue_desc&#x60; - &#x60;athlete.insuranceFrom_asc&#x60;, &#x60;athlete.insuranceFrom_desc&#x60; - &#x60;athlete.insuranceTo_asc&#x60;, &#x60;athlete.insuranceTo_desc&#x60; - &#x60;club.name_asc&#x60;, &#x60;club.name_desc&#x60;  **Examples:** - &#x60;athlete.dateOfBirth_asc&#x60; (requires expand&#x3D;athlete) - &#x60;club.name_asc, year_desc&#x60; (requires expand&#x3D;club)  **Note:** Conflicting sorts (e.g., &#x60;name_asc,name_desc&#x60;) are not allowed. 
     * @param top Maximum number of items to return
     * @param skip Number of items to skip
     * @param expand Fields to expand (multiselect). Available options: athlete, club  When expanded, the full entity objects are included in the response. Expanded fields can also be used in filter and sort expressions using dot notation. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllAccreditations(filter?: string, search?: string, orderBy?: Array<string>, top?: number, skip?: number, expand?: Array<'athlete' | 'club'>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetAllAccreditations200Response>;
    public getAllAccreditations(filter?: string, search?: string, orderBy?: Array<string>, top?: number, skip?: number, expand?: Array<'athlete' | 'club'>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetAllAccreditations200Response>>;
    public getAllAccreditations(filter?: string, search?: string, orderBy?: Array<string>, top?: number, skip?: number, expand?: Array<'athlete' | 'club'>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetAllAccreditations200Response>>;
    public getAllAccreditations(filter?: string, search?: string, orderBy?: Array<string>, top?: number, skip?: number, expand?: Array<'athlete' | 'club'>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>filter, 'filter');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>search, 'search');
        if (orderBy) {
            localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                [...orderBy].join(COLLECTION_FORMATS['csv']), 'orderBy');
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>top, 'top');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>skip, 'skip');
        if (expand) {
            localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                [...expand].join(COLLECTION_FORMATS['csv']), 'expand');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetAllAccreditations200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update accreditation status
     * Updates only the status of an accreditation. Only FEDERATION_ADMIN and APP_ADMIN can update accreditation status.
     * @param accreditationUuid UUID of the accreditation
     * @param accreditationStatusPatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchAccreditationStatus(accreditationUuid: string, accreditationStatusPatchRequest: AccreditationStatusPatchRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AccreditationDto>;
    public patchAccreditationStatus(accreditationUuid: string, accreditationStatusPatchRequest: AccreditationStatusPatchRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AccreditationDto>>;
    public patchAccreditationStatus(accreditationUuid: string, accreditationStatusPatchRequest: AccreditationStatusPatchRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AccreditationDto>>;
    public patchAccreditationStatus(accreditationUuid: string, accreditationStatusPatchRequest: AccreditationStatusPatchRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (accreditationUuid === null || accreditationUuid === undefined) {
            throw new Error('Required parameter accreditationUuid was null or undefined when calling patchAccreditationStatus.');
        }
        if (accreditationStatusPatchRequest === null || accreditationStatusPatchRequest === undefined) {
            throw new Error('Required parameter accreditationStatusPatchRequest was null or undefined when calling patchAccreditationStatus.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/accreditations/${this.configuration.encodeParam({name: "accreditationUuid", value: accreditationUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AccreditationDto>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: accreditationStatusPatchRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
