export * from './accreditations.service';
import { AccreditationsService } from './accreditations.service';
export * from './athletePhotos.service';
import { AthletePhotosService } from './athletePhotos.service';
export * from './athletes.service';
import { AthletesService } from './athletes.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './clubCoaches.service';
import { ClubCoachesService } from './clubCoaches.service';
export * from './clubRankings.service';
import { ClubRankingsService } from './clubRankings.service';
export * from './clubs.service';
import { ClubsService } from './clubs.service';
export * from './competitionGroupDefinitions.service';
import { CompetitionGroupDefinitionsService } from './competitionGroupDefinitions.service';
export * from './competitionTimetableEvents.service';
import { CompetitionTimetableEventsService } from './competitionTimetableEvents.service';
export * from './competitions.service';
import { CompetitionsService } from './competitions.service';
export * from './disciplineDefinitions.service';
import { DisciplineDefinitionsService } from './disciplineDefinitions.service';
export * from './entries.service';
import { EntriesService } from './entries.service';
export * from './finalStandings.service';
import { FinalStandingsService } from './finalStandings.service';
export * from './progression.service';
import { ProgressionService } from './progression.service';
export * from './qualificationProgressions.service';
import { QualificationProgressionsService } from './qualificationProgressions.service';
export * from './qualificationSchemes.service';
import { QualificationSchemesService } from './qualificationSchemes.service';
export * from './qualificationTiers.service';
import { QualificationTiersService } from './qualificationTiers.service';
export * from './scoringRules.service';
import { ScoringRulesService } from './scoringRules.service';
export * from './scoringSchemeBoatCoefficients.service';
import { ScoringSchemeBoatCoefficientsService } from './scoringSchemeBoatCoefficients.service';
export * from './scoringSchemes.service';
import { ScoringSchemesService } from './scoringSchemes.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './weightMeasurements.service';
import { WeightMeasurementsService } from './weightMeasurements.service';
export const APIS = [AccreditationsService, AthletePhotosService, AthletesService, AuthService, ClubCoachesService, ClubRankingsService, ClubsService, CompetitionGroupDefinitionsService, CompetitionTimetableEventsService, CompetitionsService, DisciplineDefinitionsService, EntriesService, FinalStandingsService, ProgressionService, QualificationProgressionsService, QualificationSchemesService, QualificationTiersService, ScoringRulesService, ScoringSchemeBoatCoefficientsService, ScoringSchemesService, UsersService, WeightMeasurementsService];
